[package]
name = "assembler"
version = "0.1.0"
authors = [Jesse Runner]
edition = "2018"
byteorder = "1.3.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { path = "../types" }
byteorder = {version = "1"}
